// Este archivo contiene todas las traducciones de la aplicación.
// Si quieres cambiar una palabra, solo lo haces aquí y se actualiza en toda la app.

export const IDIOMAS_DISPONIBLES = [
  { id: 'es', nombre: 'Español', icono: '🇳🇮' },
  { id: 'en', nombre: 'English', icono: '🇺🇸' },
  { id: 'pt', nombre: 'Português', icono: '🇧🇷' },
  { id: 'mi', nombre: 'Miskito', icono: 'MI' }, 
  { id: 'may', nombre: 'Mayangna', icono: 'MY' }
];

export const DICCIONARIO = {
  es: {
    // General
    seleccionaIdioma: 'Selecciona tu idioma', titulo: 'Configuración', idioma: 'Idioma',
    notificaciones: 'Notificaciones', privacidad: 'Privacidad', cerrarSesion: 'Cerrar Sesión',
    guardarIdioma: 'Guardar Idioma', iniciarSesion: 'Iniciar Sesión', usuario: 'Usuario',
    entrar: 'Entrar', navRutas: 'Rutas', navMisiones: 'Misiones', navNoticias: 'Noticias', navPerfil: 'Perfil',
    volver: 'Volver', datosCuenta: 'Datos de la Cuenta', nombreUsuario: 'Nombre de Usuario',
    nuevaContrasena: 'Nueva Contraseña', phContrasena: 'Dejar en blanco para mantener actual',
    phConfirmar: 'Confirmar nueva contraseña', guardarCambios: 'Guardar Cambios',
    
    // Ubicación
    tituloUbicacion: 'Permitir ubicación',
    descUbicacion: 'Lani necesita acceder a tu ubicación para mostrarte los destinos, misiones y negocios tradicionales más cercanos a ti.',
    btnPermitirUbicacion: 'Permitir Ubicación',
    
    // Perfil
    nivel: 'Nv.',
    puntosAcumulados: 'Puntos Acumulados',
    panelPines: 'Panel de Pines',
    descPines: 'Completa las 4 misiones de un departamento para desbloquear su insignia dorada.',
    pinDe: 'Pin de',
    desbloqueado: '¡DESBLOQUEADO!',
    progreso: 'Progreso',
    misiones: 'misiones',
    tusRedes: 'Tus Redes Sociales',
    redesGuardadas: '¡Redes sociales guardadas con éxito!',
    fbPlaceholder: 'Usuario de Facebook',
    igPlaceholder: '@usuario_instagram',
    tkPlaceholder: '@usuario_tiktok',
    guardarRedes: 'Guardar Redes',

    // Misiones
    misionesTitulo: 'Misiones',
    rutasEn: 'Rutas en',
    seleccionaDestino: 'Selecciona un destino en el mapa.',
    filtroTodas: 'todas',
    filtroTemporal: 'temporal',
    filtroPermanente: 'permanente',
    filtroComunitaria: 'comunitaria',
    pts: 'pts',
    aceptarMision: 'Aceptar misión',
    misionCompletada: 'Misión Completada',
    completarMision: 'Completar misión',
    irAlLugar: 'Ir al lugar / simular llegada',

    // --- NOTICIAS ---
    noticiasTitulo: 'Noticias Locales',
    leerMas: 'Leer más',
    tagNaturaleza: 'Naturaleza',
    tagCultura: 'Cultura',
    tagComunidad: 'Comunidad',

    // --- MAPA ---
    exploraNic: 'Explora Nicaragua',
    descMapa: 'Toca un departamento en el mapa para ver su estado actual.',
    estadoTxt: 'Estado',
    estadoAlto: 'Alta (Saturado)',
    estadoMedio: 'Moderada',
    estadoBajo: 'Despejado',
    estadoDesc: 'Desconocido',
    verMision: 'Ver misión disponible',
    tituloSost: 'Turismo Sostenible',
    descSost: 'Elige destinos con saturación "Moderada" o "Despejado" para ayudar al ecosistema local.',

    lugar_leon_desc: 'Ciudad Universitaria. Cuna de poetas y murales históricos.',
    lugar_masaya_desc: 'Cuna del Folklore. Tierra de artesanos y el imponente volcán.',
    lugar_granada_desc: 'La Gran Sultana. Arquitectura colonial a orillas del Lago Cocibolca.',

    // --- MISIONES (Títulos y Descripciones) ---
    // Granada
    mision_g1_titulo: 'Ruta del Cacao',
    mision_g1_desc: 'Visita 3 talleres artesanales de chocolate y conoce el proceso.',
    mision_g2_titulo: 'Festival de la Poesía',
    mision_g2_desc: 'Responde la trivia sobre los poetas participantes del festival.',
    mision_g3_titulo: 'Limpieza de Costas',
    mision_g3_desc: 'Únete al grupo local en las Isletas y toma una foto de tu recolección.',
    // Masaya
    mision_m1_titulo: 'Misterios del Volcán',
    mision_m1_desc: 'Completa la trivia sobre la historia del Parque Nacional Volcán Masaya.',
    mision_m2_titulo: 'Baile de Negras',
    mision_m2_desc: 'Toma una foto de los trajes tradicionales durante las fiestas patronales.',
    mision_m3_titulo: 'San Juan de Oriente',
    mision_m3_desc: 'Visita y adquiere cerámica directamente de los talleres familiares.',
    // León
    mision_l1_titulo: 'Ruta de los Murales',
    mision_l1_desc: 'Encuentra y visita 5 murales históricos de la Revolución.',
    mision_l2_titulo: 'La Gritería Chiquita',
    mision_l2_desc: 'Responde 3 preguntas sobre el origen de esta celebración.',
    mision_l3_titulo: 'Jornada Cerro Negro',
    mision_l3_desc: 'Ayuda a limpiar el sendero del volcán y sube tu evidencia.',

    // --- NOTICIAS (Títulos) ---
    news_1_titulo: 'Nueva ruta ecológica habilitada en Mombacho',
    news_2_titulo: 'Feria de Artesanías en Masaya este fin de semana',
    news_3_titulo: 'Iniciativa de limpieza en Peñitas supera meta',
  },
  
  en: {
    // General
    seleccionaIdioma: 'Select your language', titulo: 'Settings', idioma: 'Language',
    notificaciones: 'Notifications', privacidad: 'Privacy', cerrarSesion: 'Log Out',
    guardarIdioma: 'Save Language', iniciarSesion: 'Login', usuario: 'Username',
    entrar: 'Sign In', navRutas: 'Routes', navMisiones: 'Missions', navNoticias: 'News', navPerfil: 'Profile',
    volver: 'Back', datosCuenta: 'Account Data', nombreUsuario: 'Username',
    nuevaContrasena: 'New Password', phContrasena: 'Leave blank to keep current',
    phConfirmar: 'Confirm new password', guardarCambios: 'Save Changes',
    
    // Ubicación
    tituloUbicacion: 'Allow location',
    descUbicacion: 'Lani needs access to your location to show you the closest destinations, missions, and traditional businesses.',
    btnPermitirUbicacion: 'Allow Location',
    
    // Perfil
    nivel: 'Lvl.',
    puntosAcumulados: 'Accumulated Points',
    panelPines: 'Pins Panel',
    descPines: 'Complete the 4 missions of a department to unlock its golden badge.',
    pinDe: 'Pin for',
    desbloqueado: 'UNLOCKED!',
    progreso: 'Progress',
    misiones: 'missions',
    tusRedes: 'Your Social Networks',
    redesGuardadas: 'Social networks successfully saved!',
    fbPlaceholder: 'Facebook Username',
    igPlaceholder: '@instagram_user',
    tkPlaceholder: '@tiktok_user',
    guardarRedes: 'Save Networks',

    // Misiones
    misionesTitulo: 'Missions',
    rutasEn: 'Routes in',
    seleccionaDestino: 'Select a destination on the map.',
    filtroTodas: 'all',
    filtroTemporal: 'temporary',
    filtroPermanente: 'permanent',
    filtroComunitaria: 'community',
    pts: 'pts',
    aceptarMision: 'Accept mission',
    misionCompletada: 'Mission Completed',
    completarMision: 'Complete mission',
    irAlLugar: 'Go to location / simulate arrival',

    // --- NOTICIAS ---
    noticiasTitulo: 'Local News',
    leerMas: 'Read more',
    tagNaturaleza: 'Nature',
    tagCultura: 'Culture',
    tagComunidad: 'Community',

    // --- MAPA ---
    exploraNic: 'Explore Nicaragua',
    descMapa: 'Tap a department on the map to see its current status.',
    estadoTxt: 'Status',
    estadoAlto: 'High (Crowded)',
    estadoMedio: 'Moderate',
    estadoBajo: 'Clear',
    estadoDesc: 'Unknown',
    verMision: 'View available mission',
    tituloSost: 'Sustainable Tourism',
    descSost: 'Choose destinations with "Moderate" or "Clear" saturation to help the local ecosystem.',

    lugar_leon_desc: 'University City. Cradle of poets and historic murals.',
    lugar_masaya_desc: 'Cradle of Folklore. Land of artisans and the imposing volcano.',
    lugar_granada_desc: 'The Great Sultana. Colonial architecture on the shores of Lake Cocibolca.',

    mision_g1_titulo: 'Cacao Route',
    mision_g1_desc: 'Visit 3 artisanal chocolate workshops and learn the process.',
    mision_g2_titulo: 'Poetry Festival',
    mision_g2_desc: 'Answer the trivia about the poets participating in the festival.',
    mision_g3_titulo: 'Coastal Cleanup',
    mision_g3_desc: 'Join the local group in the Isletas and take a photo of your collection.',
    mision_m1_titulo: 'Volcano Mysteries',
    mision_m1_desc: 'Complete the trivia about the history of the Masaya Volcano National Park.',
    mision_m2_titulo: 'Dance of the Black Women',
    mision_m2_desc: 'Take a photo of the traditional costumes during the patron saint festivities.',
    mision_m3_titulo: 'San Juan de Oriente',
    mision_m3_desc: 'Visit and acquire ceramics directly from family workshops.',
    mision_l1_titulo: 'Murals Route',
    mision_l1_desc: 'Find and visit 5 historic murals of the Revolution.',
    mision_l2_titulo: 'The Little Gritería',
    mision_l2_desc: 'Answer 3 questions about the origin of this celebration.',
    mision_l3_titulo: 'Cerro Negro Journey',
    mision_l3_desc: 'Help clean the volcano trail and upload your evidence.',

    news_1_titulo: 'New ecological route opened in Mombacho',
    news_2_titulo: 'Handicrafts Fair in Masaya this weekend',
    news_3_titulo: 'Cleanup initiative in Peñitas exceeds goal',
  },

  pt: {
    // General
    seleccionaIdioma: 'Selecione seu idioma', titulo: 'Configurações', idioma: 'Idioma',
    notificaciones: 'Notificações', privacidad: 'Privacidade', cerrarSesion: 'Sair',
    guardarIdioma: 'Salvar Idioma', iniciarSesion: 'Entrar', usuario: 'Usuário',
    entrar: 'Começar Aventura', navRutas: 'Rotas', navMisiones: 'Missões', navNoticias: 'Notícias', navPerfil: 'Perfil',
    volver: 'Voltar', datosCuenta: 'Dados da Conta', nombreUsuario: 'Nome de Usuário',
    nuevaContrasena: 'Nova Senha', phContrasena: 'Deixe em branco para manter a atual',
    phConfirmar: 'Confirmar nova senha', guardarCambios: 'Salvar Alterações',
    
    // Ubicación
    tituloUbicacion: 'Permitir localização',
    descUbicacion: 'Lani precisa acessar sua localização para mostrar os destinos, missões e negócios tradicionais mais próximos de você.',
    btnPermitirUbicacion: 'Permitir Localização',
    
    // Perfil
    nivel: 'Nv.',
    puntosAcumulados: 'Pontos Acumulados',
    panelPines: 'Painel de Pins',
    descPines: 'Complete as 4 missões de um departamento para desbloquear seu distintivo dourado.',
    pinDe: 'Pin de',
    desbloqueado: 'DESBLOQUEADO!',
    progreso: 'Progresso',
    misiones: 'missões',
    tusRedes: 'Suas Redes Sociais',
    redesGuardadas: 'Redes sociais salvas com sucesso!',
    fbPlaceholder: 'Usuário do Facebook',
    igPlaceholder: '@usuario_instagram',
    tkPlaceholder: '@usuario_tiktok',
    guardarRedes: 'Salvar Redes',

    // Misiones
    misionesTitulo: 'Missões',
    rutasEn: 'Rotas em',
    seleccionaDestino: 'Selecione um destino no mapa.',
    filtroTodas: 'todas',
    filtroTemporal: 'temporária',
    filtroPermanente: 'permanente',
    filtroComunitaria: 'comunitária',
    pts: 'pts',
    aceptarMision: 'Aceitar missão',
    misionCompletada: 'Missão Concluída',
    completarMision: 'Concluir missão',
    irAlLugar: 'Ir ao local / simular chegada',

    // --- NOTICIAS ---
    noticiasTitulo: 'Notícias Locais',
    leerMas: 'Ler mais',
    tagNaturaleza: 'Natureza',
    tagCultura: 'Cultura',
    tagComunidad: 'Comunidade',

    exploraNic: 'Explore a Nicarágua',
    descMapa: 'Toque em um departamento no mapa para ver seu estado atual.',
    estadoTxt: 'Estado',
    estadoAlto: 'Alta (Lotado)',
    estadoMedio: 'Moderada',
    estadoBajo: 'Livre',
    estadoDesc: 'Desconhecido',
    verMision: 'Ver missão disponível',
    tituloSost: 'Turismo Sustentável',
    descSost: 'Escolha destinos com saturação "Moderada" ou "Livre" para ajudar o ecossistema local.',

    lugar_leon_desc: 'Cidade Universitária. Berço de poetas e murais históricos.',
    lugar_masaya_desc: 'Berço do Folclore. Terra de artesãos e do imponente vulcão.',
    lugar_granada_desc: 'A Grande Sultana. Arquitetura colonial às margens do Lago Cocibolca.',

    mision_g1_titulo: 'Rota do Cacau',
    mision_g1_desc: 'Visite 3 oficinas artesanais de chocolate e conheça o processo.',
    mision_g2_titulo: 'Festival de Poesia',
    mision_g2_desc: 'Responda às perguntas sobre os poetas participantes do festival.',
    mision_g3_titulo: 'Limpeza da Costa',
    mision_g3_desc: 'Junte-se ao grupo local nas Isletas e tire uma foto da sua coleta.',
    mision_m1_titulo: 'Mistérios do Vulcão',
    mision_m1_desc: 'Complete o questionário sobre a história do Parque Nacional Vulcão Masaya.',
    mision_m2_titulo: 'Dança das Negras',
    mision_m2_desc: 'Tire uma foto dos trajes tradicionais durante as festas padroeiras.',
    mision_m3_titulo: 'San Juan de Oriente',
    mision_m3_desc: 'Visite e adquira cerâmica diretamente das oficinas familiares.',
    mision_l1_titulo: 'Rota dos Murais',
    mision_l1_desc: 'Encontre e visite 5 murais históricos da Revolução.',
    mision_l2_titulo: 'A Gritería Chiquita',
    mision_l2_desc: 'Responda a 3 perguntas sobre a origem desta celebração.',
    mision_l3_titulo: 'Jornada Cerro Negro',
    mision_l3_desc: 'Ajude a limpar a trilha do vulcão e envie sua evidência.',

    news_1_titulo: 'Nova rota ecológica ativada em Mombacho',
    news_2_titulo: 'Feira de Artesanato em Masaya neste fim de semana',
    news_3_titulo: 'Iniciativa de limpeza em Peñitas supera a meta',
  },

  mi: {
    // General 
    seleccionaIdioma: 'Bila plikaya', titulo: 'Dawanka', idioma: 'Bila',
    notificaciones: 'Walaya', privacidad: 'Privacidad', cerrarSesion: 'Takaya',
    guardarIdioma: 'Bila Brika', iniciarSesion: 'Dimaia', usuario: 'Wina',
    entrar: 'Dim', navRutas: 'Yabalka', navMisiones: 'Wark', navNoticias: 'Nius', navPerfil: 'Dawanka',
    volver: 'Kli wiaia', datosCuenta: 'Bila Dukiya', nombreUsuario: 'Wina Nina',
    nuevaContrasena: 'Paswot Raya', phContrasena: 'Swis baman',
    phConfirmar: 'Paswot raya kasak', guardarCambios: 'Brikaia',
    
    tituloUbicacion: 'Permitir ubicación',
    descUbicacion: 'Lani necesita acceder a tu ubicación para mostrarte destinos.',
    btnPermitirUbicacion: 'Permitir Ubicación',
    nivel: 'Nv.',
    puntosAcumulados: 'Puntos Acumulados',
    panelPines: 'Panel de Pines',
    descPines: 'Completa las 4 misiones de un departamento para desbloquear su insignia.',
    pinDe: 'Pin de',
    desbloqueado: '¡DESBLOQUEADO!',
    progreso: 'Progreso',
    misiones: 'misiones',
    tusRedes: 'Tus Redes Sociales',
    redesGuardadas: '¡Guardado!',
    fbPlaceholder: 'Usuario de Facebook',
    igPlaceholder: '@usuario_instagram',
    tkPlaceholder: '@usuario_tiktok',
    guardarRedes: 'Guardar Redes',

    // Misiones
    misionesTitulo: 'Wark',
    rutasEn: 'Yabalka',
    seleccionaDestino: 'Kumi yabalka wali',
    filtroTodas: 'maikira',
    filtroTemporal: 'darang',
    filtroPermanente: 'samni',
    filtroComunitaria: 'baha',
    pts: 'pts',
    aceptarMision: 'Wark takbia',
    misionCompletada: 'Wark kasak',
    completarMision: 'Wark brikaia',
    irAlLugar: 'Lain wina yaia',

    // --- NOTICIAS ---
    noticiasTitulo: 'Sturi Nani',
    leerMas: 'Kau kaikaia',
    tagNaturaleza: 'Tasba',
    tagCultura: 'Natka',
    tagComunidad: 'Tawan',

    exploraNic: 'Nicaragua Kaikaia',
    descMapa: 'Tawan kumi map ra klikaia sip mita storka kaikaia.',
    estadoTxt: 'Baha',
    estadoAlto: 'Upla Man (Saturado)',
    estadoMedio: 'Pitka',
    estadoBajo: 'Klin (Despejado)',
    estadoDesc: 'Kaiki Apia',
    verMision: 'Wark kaikaia',
    tituloSost: 'Tasba Pura Kaikaia',
    descSost: 'Tawan "Pitka" apia kaka "Klin" plikaia, tasba nani help munaia.',

    lugar_leon_desc: 'Skul Tara Tawan. Strika uplika nani baman bara sturi paskan tasbaya.',
    lugar_masaya_desc: 'Natka paskan tasbaya. Wark dauki uplika nani bara il tara wina.',
    lugar_granada_desc: 'La Gran Sultana. Urak kumi damni Cocibolca laya unra.',

    mision_g1_titulo: 'Cacao Yabalni',
    mision_g1_desc: 'Chocolate paski wark 3 kaiks bara natka lan taks.',
    mision_g2_titulo: 'Strika Yuwa Tara',
    mision_g2_desc: 'Strika uplika nani sturika makabi walbia kaka pana wis.',
    mision_g3_titulo: 'Laya Un Klin Munaia',
    mision_g3_desc: 'Isleta uplika nani wal dimaia bara lilka kumi briaia dusa nani paskan wina.',
    mision_m1_titulo: 'Il Tara Sturika',
    mision_m1_desc: 'Masaya Il Tara Parkeka sturika makabi walbia baha pana wis.',
    mision_m2_titulo: 'Baile de Negras',
    mision_m2_desc: 'Kwata natka lalka kumi briaia u yuwa tara piua ra.',
    mision_m3_titulo: 'San Juan de Oriente',
    mision_m3_desc: 'Smu paskan uba wapaia bara smu atkaia familya nani wina.',
    mision_l1_titulo: 'Mural Yabalni',
    mision_l1_desc: 'Revolución muralika 5 pliki kaiks.',
    mision_l2_titulo: 'La Gritería Chiquita',
    mision_l2_desc: 'Naha piua sturika wina makabi walan 3 pana wis.',
    mision_l3_titulo: 'Cerro Negro Yabalni',
    mision_l3_desc: 'Il tara yabalni klin munaia help munaia bara lilkika mangkaia.',

    news_1_titulo: 'Mombacho ra tasba yabalni raya kumi paskan',
    news_2_titulo: 'Naha wihki Masaya ra Artesanía Feria ka daukaia',
    news_3_titulo: 'Peñitas ra klin munaia warkka nani purara tawan',
  },

  may: {
    // General 
    seleccionaIdioma: 'Yulni', titulo: 'Configuración', idioma: 'Yulni',
    notificaciones: 'Notificaciones', privacidad: 'Privacidad', cerrarSesion: 'Cerrar Sesión',
    guardarIdioma: 'Guardar Yulni', iniciarSesion: 'Entrar', usuario: 'Usuario',
    entrar: 'Entrar', navRutas: 'Rutas', navMisiones: 'Misiones', navNoticias: 'Noticias', navPerfil: 'Perfil',
    volver: 'Kalyan', datosCuenta: 'Datos', nombreUsuario: 'Uyuni',
    nuevaContrasena: 'Paswot', phContrasena: 'Blank',
    phConfirmar: 'Paswot', guardarCambios: 'Yamna',
    
    tituloUbicacion: 'Permitir ubicación',
    descUbicacion: 'Lani necesita acceder a tu ubicación para mostrarte destinos.',
    btnPermitirUbicacion: 'Permitir Ubicación',
    nivel: 'Nv.',
    puntosAcumulados: 'Puntos Acumulados',
    panelPines: 'Panel de Pines',
    descPines: 'Completa las 4 misiones de un departamento para desbloquear su insignia.',
    pinDe: 'Pin de',
    desbloqueado: '¡DESBLOQUEADO!',
    progreso: 'Progreso',
    misiones: 'misiones',
    tusRedes: 'Tus Redes Sociales',
    redesGuardadas: '¡Guardado!',
    fbPlaceholder: 'Usuario de Facebook',
    igPlaceholder: '@usuario_instagram',
    tkPlaceholder: '@usuario_tiktok',
    guardarRedes: 'Guardar Redes',

    // Misiones
    misionesTitulo: 'Misiones',
    rutasEn: 'Rutas',
    seleccionaDestino: 'Yulni map.',
    filtroTodas: 'yaka',
    filtroTemporal: 'temporal',
    filtroPermanente: 'permanente',
    filtroComunitaria: 'comunitaria',
    pts: 'pts',
    aceptarMision: 'Aceptar misión',
    misionCompletada: 'Misión Completada',
    completarMision: 'Completar misión',
    irAlLugar: 'Ir al lugar',

    // --- NOTICIAS ---
    noticiasTitulo: 'Yulna Nani',
    leerMas: 'Kau talnin',
    tagNaturaleza: 'Sau',
    tagCultura: 'Natka',
    tagComunidad: 'Asang',

    // --- MAPA ---
    exploraNic: 'Nicaragua Talnin',
    descMapa: 'Asang as map ra talnin sip mankaia.',
    estadoTxt: 'Dah',
    estadoAlto: 'Upla Tayak (Saturado)',
    estadoMedio: 'Baisa',
    estadoBajo: 'Yamni (Despejado)',
    estadoDesc: 'Talwi Apia',
    verMision: 'Wark talnin',
    tituloSost: 'Sau Pura Talnin',
    descSost: 'Asang "Baisa" o "Yamni" talnin, sau yaka yamni maknin.',

    lugar_leon_desc: 'Asang Skulni Tara. Yulwi nani yabalni dutna sturini balna.',
    lugar_masaya_desc: 'Natka asangni. Wark yamwa nani dis ilni tara.',
    lugar_granada_desc: 'La Gran Sultana. U hiling was Cocibolca unni ra.',

    mision_g1_titulo: 'Cacao Yabalni',
    mision_g1_desc: 'Chocolate yamwa 3 talna yaka natka talwi.',
    mision_g2_titulo: 'Yulwi Yuwa Tara',
    mision_g2_desc: 'Yulwi nani sturini makabi walyah kalyah yulnin.',
    mision_g3_titulo: 'Was Unni Yamni Maknin',
    mision_g3_desc: 'Isleta uplika balna karak dawak lilka as wakaia bas nani dawak.',
    mision_m1_titulo: 'Il Tara Sturini',
    mision_m1_desc: 'Masaya Il Tara Parkeni sturini makabi walyah yulnin.',
    mision_m2_titulo: 'Baile de Negras',
    mision_m2_desc: 'Asang natkani lilka as wakaia yuwa tara dani ra.',
    mision_m3_titulo: 'San Juan de Oriente',
    mision_m3_desc: 'Sau yamni talnin dawak atnin muihni balna wina.',
    mision_l1_titulo: 'Mural Yabalni',
    mision_l1_desc: 'Revolución muralni 5 talwi talnin.',
    mision_l2_titulo: 'La Gritería Chiquita',
    mision_l2_desc: 'Adika yuwa sturini makabi walyah 3 kalyah yulnin.',
    mision_l3_titulo: 'Cerro Negro Yabalni',
    mision_l3_desc: 'Il tara yabalni yamni maknin dawak lilka mankanin.',

    news_1_titulo: 'Mombacho ra sau yabalni raya as yamtik',
    news_2_titulo: 'Adika wihki Masaya ra Artesanía Feria yamnin',
    news_3_titulo: 'Peñitas ra yamni maknin warkni balna uba yamni yamtik',
  }
};